### ISSUE TITLE
2.0 beta.8 doesn't report all errors

### ISSUE THREAD

**Issue by hubertlepicki** [appsignal/appsignal-elixir#579]
Hey there!

I am trying out the 2.0 (beta.8) version of upcoming Appsignal, mostly because of the logger backend and it would be very beneficial for us in terms of cutting extra manual instrumentation we have to do to capture all errors in the system. We still want to have own instrumentation here and there so we can decorate the errors with parameters and metadata when we for example run background jobx.

There is couple issues (that I report in separate tickets). First issue is that I don't seem to be receiving all samples.

I have added appsignal 2.0 with the following lines to my app:

```
      {:appsignal, "2.0.0-beta.8"},
      {:appsignal_phoenix, "2.0.0-beta.6"},
```

And Now I am now reporting some exceptions from iex console:

```
iex(a@127.0.0.1)22> spawn fn -> Appsignal.instrument fn span -> Appsignal.Span.set_namespace(span, "background") |> Appsignal.Span.set_sample_dat
a("params", %{my_param: "my_value"}) |> Appsignal.Span.set_name("Exq/error") |> Appsignal.Span.add_error(:error, "Happened", []) |> Appsignal.Tra
cer.close_span(); end; end
#PID<0.1693.0>
iex(a@127.0.0.1)23> spawn fn -> Appsignal.instrument fn span -> Appsignal.Span.set_namespace(span, "background") |> Appsignal.Span.set_sample_data("params", %{my_param: "my_value"}) |> Appsignal.Span.set_name("Exq/error") |> Appsignal.Span.add_error(:error, "Happened", []) |> Appsignal.Tracer.close_span(); end; end
#PID<0.1697.0>
iex(a@127.0.0.1)24> spawn fn -> Appsignal.instrument fn span -> Appsignal.Span.set_namespace(span, "background") |> Appsignal.Span.set_sample_data("params", %{my_param: "my_value"}) |> Appsignal.Span.set_name("Exq/error") |> Appsignal.Span.add_error(:error, "Happened", []) |> Appsignal.Tracer.close_span(); end; end
#PID<0.1699.0>
iex(a@127.0.0.1)25> spawn fn -> Appsignal.instrument fn span -> Appsignal.Span.set_namespace(span, "background") |> Appsignal.Span.set_sample_data("params", %{my_param: "my_value"}) |> Appsignal.Span.set_name("Exq/error") |> Appsignal.Span.add_error(:error, "Happened", []) |> Appsignal.Tracer.close_span(); end; end
#PID<0.1701.0>
iex(a@127.0.0.1)26> spawn fn -> Appsignal.instrument fn span -> Appsignal.Span.set_namespace(span, "background") |> Appsignal.Span.set_sample_data("params", %{my_param: "my_value"}) |> Appsignal.Span.set_name("Exq/error") |> Appsignal.Span.add_error(:error, "Happened", []) |> Appsignal.Tracer.close_span(); end; end
#PID<0.1703.0>
```

As you can see above, I have reported 5 times error "Happened" using `Appsignal.Span.add_error/4`.

See the screenshot below, the error clearly happened 5 times but I have only two samples in my dashboard:
![appsignal1](https://user-images.githubusercontent.com/33274/91281487-70aa5100-e788-11ea-8e0c-1e15994ea7b6.png)

Is this normal as AppSignal somehow deduplicates / groups error instances? Or I should see all exception instances here?

**Comment by xadamy** [comment]
@hubertlepicki Thanks for reporting this and #580! Jeff is out of office this week, but I will ensure both issues end up on his desk when he returns next week. Cheers from your friends at AppSignal, we hope you are well! ✌️

**Comment by hubertlepicki** [comment]
@xadamy cool. that's great we are not in a hurry anyway. I have shelved the ticket to upgrade to 2.0 for now and we'll get back to it. It is entirely possible I am doing something wrong (on both issues)

**Comment by jeffkreeftmeijer** [comment]
Hey @hubertlepicki, 

Thanks again for helping us test 2.0, and thanks for letting us know about this. We're looking into why (and in which part of the stack) this could happen, and we'll be back with you once we know more. We'll be in touch!

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700002289

**Comment by jeffkreeftmeijer** [comment]
Hey @hubertlepicki,

We've been able to identify this issue, and the one described in #579, and we've pushed some fixes to our processing pipeline. We've also had to make some changes to the agent shipped with the current Elixir beta's, so we've released 2.0.0-beta.10 last week.

Could you try updating your dependency on `:appsignal` (`mix deps.update appsignal`), and try the test case you described above again? You should now receive all errors you send this way.

Thanks once more for taking the time to test our beta versions and reporting this issue!

**Comment by hubertlepicki** [comment]
Yep, testing this now.

**Comment by hubertlepicki** [comment]
It's better! What I am seeing now is that the errors get correctly reported and show up in the list of smamples in *details* of the given error in my Dashboard -> Errors in AppSignal.
![error-2](https://user-images.githubusercontent.com/33274/96844112-68e8ef00-144f-11eb-9f04-d353dca1b02c.png)

What is out of sync, however, is that on the list of Errors I can still see only fraction of errors count, which I think has something to do with cache busting or something similar? 
![error-1](https://user-images.githubusercontent.com/33274/96844184-7f8f4600-144f-11eb-8196-b164b655d22b.png)

**Comment by hubertlepicki** [comment]
Just an update in case this was some issue with just delaying the update on the dashboard: it doesn't seem like it is the case. It's been 24 hours since these events happened and it still shows number '2" as total/in deploy versus 30 samples when you go to the details.

**Comment by jeffkreeftmeijer** [comment]
A quick update to this; this seems to be an issue in our processing backend. We have an internal issue open for this (private link: https://github.com/appsignal/appsignal-processor-rs/issues/448), and we'll update this issue when we learn more on that side. This shouldn't require any changes to the Appsignal for Elixir library.

**Comment by jeffkreeftmeijer** [comment]
Hey @hubertlepicki,

We’ve just released version 2.0.3, which includes a fix in our agent, which hooks into a fix we deployed in our processor. Could you upgrade to the latest version, and reopen this issue is you run into this again?

Thanks again for reporting this!
